### ISSUE TITLE
Thesaurus?

### ISSUE THREAD

**Issue by trifle** [gh640/SublimeMacDictionary#10]
Hi, thanks for the great plugin! I love the macOS dictionary and use the hell out of it.
One thing that I particularly like is using the british AND us dictionary AND thesaurus alongside each other.
Would it be possible to add this to the plugin?

**Comment by trifle** [comment]
Okay, I poked around in ConsultMacDictionary.py ...
```
import DictionaryServices
dir(DictionaryServices)
```
... the horror! What the hell do they even export there!

The  next surprise was that python2 segfaulted on me when I tried supplying some strings to `DCSCopyTextDefinition`as DICTIONARY parameter.

So I guess it's possible to add a configuration switch for the dictionary to use, but not quite a 5 minute thing.

**edit**: premature celebration ... the [apple docs](https://developer.apple.com/documentation/coreservices/1446842-dcscopytextdefinition) say:

> dictionary
>    This parameter is reserved for future use, so pass NULL. Dictionary Services searches in all active dictionaries.

**Comment by gh640** [comment]
Thank you for sharing your idea!

I saw the same page when I implemented this plugin. As you found, unfortunately it seems that Apple doesn't provide the function to select the dictionary programatically... :(

**Comment by trifle** [comment]
I have one minor suggestion, @gh640.

There is a workaround that can be used to switch the dictionary.
As per Apple's documentation, `DCSCopyTextDefinition` searches through the installed dictionaries in order and returns the first match found.

It is possible to change the order (and, strangely, also the name!) of the dictionaries. In order to do this, we need to go to the preferences and drag the entries in the desired order:

<img width="448" alt="screenshot 2019-03-01 at 11 35 44" src="https://user-images.githubusercontent.com/450916/53633075-c3985c00-3c16-11e9-9f2c-c1749a0fe8e4.png">

Once that is done, your plugin will return matches from the first dictionary if there are any:

<img width="393" alt="screenshot 2019-03-01 at 11 35 28" src="https://user-images.githubusercontent.com/450916/53633117-e0349400-3c16-11e9-96ba-a8b2d7207484.png">

It might be worth mentioning this in the documentation!

Thanks again for the wonderful plugin!

**edit**: A restart (of Dictionary.app, Sublime and possibly the entire system) might be necessary before the new order of dictionaries is recognized.

**Comment by gh640** [comment]
@trifle , thanks for the detailed explanation and suggestion. I see! 

It must be a good knowledge for all the users! Could you make a PR for this? I would be grateful if you would do :D

**Comment by trifle** [comment]
Gladly, see above. I hope this is what you had in mind.

**Comment by gh640** [comment]
Oh, it's more than I expected! Thanks :D
