### ISSUE TITLE
Dependency mdpopups package is no longer available

### ISSUE THREAD

**Issue by sammcj** [gh640/SublimeMacDictionary#6]
As per https://github.com/facelessuser/sublime-markdown-popups/issues/55 the 'mdpopups' package is no longer available in Sublime Package Manager.

The result is that when this package is installed, it no longer installs mdpopups as a dependency and thus does not function.

**Comment by gh640** [comment]
Hi, @sammcj 

`mdpopups` is not a package but a dependency.

> Dependencies are non-user-visible packages that contain binaries, shared libraries or Python modules.

https://packagecontrol.io/docs/dependencies

Dependencies a package depends on are automatically installed and you don't need to worry about that, I think. I tried installing this package through Package Control and there is not anything wrong.

If you met any problem on installation, please let me know the details. Thanks 😃

**Comment by sammcj** [comment]
Oh! Geez, sorry I missed that!

**Comment by gh640** [comment]
Oh, I see! Thank you for trying the package :)
